#!/bin/sh
# Writes <dir>/requirements.txt from <dir>/requirements.in for a seed one-shot: every package pinned to one version
# with the sha256 of the wheel pip downloads for the given image, so `pip install --require-hashes` installs those
# wheels and nothing else. It then installs the result into a fresh virtual environment and runs `pip check`, so a
# requirements.in that misses a dependency fails here and not in the seed. Run it again after any change to
# requirements.in, and never edit requirements.txt by hand.
#   sh docker/lock-requirements.sh <dir> <python image pinned by digest>
set -eu
dir=$(cd "$1" && pwd)
image="$2"
docker run --rm --memory=2g --cpus=2 --user "$(id -u):$(id -g)" -e HOME=/tmp -v "$dir:/w" -w /w "$image" sh -eu -c '
  pip download --quiet --disable-pip-version-check --no-cache-dir --no-deps --only-binary=:all: \
    -d /tmp/wheels -r requirements.in
  [ "$(ls /tmp/wheels | wc -l)" -eq "$(grep -c "==" requirements.in)" ] || { echo "one wheel per pin expected" >&2; exit 1; }
  {
    echo "# Generated by docker/lock-requirements.sh from requirements.in for $0; never edit by hand."
    for wheel in /tmp/wheels/*.whl; do
      file=${wheel##*/}
      name=${file%%-*}
      rest=${file#*-}
      version=${rest%%-*}
      hash=$(python -c "import hashlib, sys; print(hashlib.sha256(open(sys.argv[1], \"rb\").read()).hexdigest())" "$wheel")
      echo "$name==$version --hash=sha256:$hash"
    done
  } >requirements.txt.new
  python -m venv /tmp/check
  /tmp/check/bin/pip install --quiet --disable-pip-version-check --no-cache-dir --require-hashes -r requirements.txt.new
  /tmp/check/bin/pip check
  mv requirements.txt.new requirements.txt
' "$image"
