/**
 * The Oxia provider's routing (SB1-5.2, SB1-5.6): the shape check of a shard-assignment message, the XXH3 port and
 * `shardFor`.
 *
 * The hash cases read `tests/fixtures/oxia/xxh3-vectors.json`, generated by `@node-rs/xxhash` outside the repository
 * and cross-checked through a real server whose keys the Go CLI wrote; no vector is computed by the code under test.
 * The literal server and research vectors are asserted as well, so an edited fixture cannot weaken a case.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { OxiaEndpoint, OxiaShard, OxiaSnapshot } from "@/lib/db/providers/keyvalue/oxia/client";
import { OXIA_LEADER_MAX_BYTES, OXIA_MAX_SHARDS } from "@/lib/db/providers/keyvalue/oxia/constants";
import {
  oxiaHash,
  SNAPSHOT_PROBLEM_REASONS,
  shardFor,
  validateAssignments,
  type WireAssignments,
  type WireShardAssignment,
  xxh3Low32,
} from "@/lib/db/providers/keyvalue/oxia/routing";

interface TextVector {
  readonly text: string;
  readonly low32: number;
}
interface CrossCheck {
  readonly image: string;
  readonly digest: string;
  readonly shards: number;
  readonly cliCommand: string;
  readonly keys: number;
  readonly onPredictedShard: number;
}
interface VectorFixture {
  readonly header: {
    readonly tool: string;
    readonly toolVersion: string;
    readonly node: string;
    readonly command: string;
    readonly crossCheck: CrossCheck;
  };
  readonly server: readonly TextVector[];
  readonly measured: readonly TextVector[];
  readonly generated: readonly { readonly length: number; readonly xxh3: string }[];
}

const fixture: VectorFixture = JSON.parse(
  readFileSync(join(import.meta.dir, "../../../fixtures/oxia/xxh3-vectors.json"), "utf8"),
);

/** A stand-in for T11's parseLeaderAddress: host:port with a port from 1 to 65535, nothing else. */
const parseLeader = (raw: string): OxiaEndpoint | undefined => {
  const match = /^([a-z0-9.-]+):([1-9][0-9]{0,4})$/.exec(raw);
  if (match === null || Number(match[2]) > 65_535) return undefined;
  return { host: match[1] as string, port: Number(match[2]) };
};
/** `count` shards that split the hash space evenly, as the server's GenerateShards does. */
function wire(
  count: number,
  edit: (assignments: WireShardAssignment[]) => void = () => undefined,
  router = "XXHASH3",
): WireAssignments {
  const bucket = Math.floor(0xffffffff / count) + 1;
  const assignments: WireShardAssignment[] = Array.from({ length: count }, (_, index) => ({
    shard: String(index),
    leader: "oxia-0.example:6648",
    int32_hash_range: {
      min_hash_inclusive: index * bucket,
      max_hash_inclusive: index === count - 1 ? 0xffffffff : (index + 1) * bucket - 1,
    },
  }));
  edit(assignments);
  return { namespaces: { default: { assignments, shard_key_router: router } } };
}
const problemOf = (message: WireAssignments, namespace = "default") => {
  const answer = validateAssignments(message, namespace, parseLeader);
  return "problem" in answer ? answer.problem : undefined;
};
/** Replaces the first assignment's hash range. */
const withRange = (min: number, max: number) => (assignments: WireShardAssignment[]) => {
  assignments[0] = {
    ...assignments[0],
    int32_hash_range: { min_hash_inclusive: min, max_hash_inclusive: max },
  } as WireShardAssignment;
};
/** Sets the ids in order over the assignments. */
const withIds =
  (...ids: string[]) =>
  (assignments: WireShardAssignment[]) => {
    ids.forEach((id, index) => {
      assignments[index] = { ...assignments[index], shard: id } as WireShardAssignment;
    });
  };
/** Sets every leader. */
const withLeader = (leader: string) => (assignments: WireShardAssignment[]) => {
  assignments.forEach((assignment, index) => {
    assignments[index] = { ...assignment, leader };
  });
};
/** Moves the second assignment's min by `delta`. */
const shiftSecondMin = (delta: number) => (assignments: WireShardAssignment[]) => {
  const second = assignments[1] as WireShardAssignment;
  const range = second.int32_hash_range as NonNullable<WireShardAssignment["int32_hash_range"]>;
  assignments[1] = { ...second, int32_hash_range: { ...range, min_hash_inclusive: range.min_hash_inclusive + delta } };
};

const LEADER = { host: "h", port: 1, address: "h:1", bootstrap: true };
/** A snapshot of the given inclusive ranges, ids "0", "1", ... unless given. */
function snapshot(ranges: readonly (readonly [number, number])[], ids?: readonly string[]): OxiaSnapshot {
  const shards: OxiaShard[] = ranges.map(([minHash, maxHash], index) => ({
    id: ids?.[index] ?? String(index),
    minHash,
    maxHash,
    leader: LEADER,
  }));
  return { namespace: "default", shards, readAt: 0 };
}
/** An even split of the hash space into `count` shards. */
function evenSnapshot(count: number, ids?: readonly string[]): OxiaSnapshot {
  const bucket = Math.floor(0xffffffff / count) + 1;
  const ranges = Array.from(
    { length: count },
    (_, index) => [index * bucket, index === count - 1 ? 0xffffffff : (index + 1) * bucket - 1] as const,
  );
  return snapshot(ranges, ids);
}

const SERVER_VECTORS: Record<string, number> = { foo: 125730186, bar: 2687685474, baz: 862947621 };
const RESEARCH_VECTORS: Record<string, number> = {
  "": 953390274,
  a: 513166879,
  "key-1": 1795303929,
  "/a/b": 973649257,
  ünïcode: 3621230215,
  "__oxia/x": 2206503242,
};

describe("validateAssignments (C11)", () => {
  test("a valid map answers its shards sorted by minHash", () => {
    const answer = validateAssignments(
      wire(3, (a) => a.reverse()),
      "default",
      parseLeader,
    );
    if (!("shards" in answer)) throw new Error(`expected shards, got ${answer.problem}`);
    expect(answer.shards.map((shard) => shard.id)).toEqual(["0", "1", "2"]);
    expect(answer.shards[0]?.minHash).toBe(0);
    expect(answer.shards[2]?.maxHash).toBe(4294967295);
    for (const shard of answer.shards) {
      expect(shard.leaderRaw).toBe("oxia-0.example:6648");
      expect(shard.leader).toEqual({ host: "oxia-0.example", port: 6648 });
    }
  });

  test("the namespace is missing", () => {
    expect(problemOf(wire(1), "other")).toBe("namespace-missing");
  });

  test("a namespace named like an Object member is missing, not found on the prototype", () => {
    for (const namespace of ["constructor", "__proto__", "toString"]) {
      expect(problemOf(wire(1), namespace)).toBe("namespace-missing");
    }
  });

  test("no shards", () => {
    expect(problemOf(wire(1, (a) => a.splice(0)))).toBe("no-shards");
  });

  test("1,024 shards pass and 1,025 are too many", () => {
    expect(problemOf(wire(OXIA_MAX_SHARDS))).toBeUndefined();
    expect(problemOf(wire(OXIA_MAX_SHARDS + 1))).toBe("too-many-shards");
  });

  test("a shard id is a 64-bit integer in decimal", () => {
    // A 20-digit id that sorts below the greatest int64 as text is refused by its length.
    for (const id of [
      "",
      "01",
      "-1",
      "1.5",
      "1e3",
      " 1",
      "9223372036854775808",
      "99999999999999999999",
      "10000000000000000000",
    ]) {
      expect(problemOf(wire(1, withIds(id)))).toBe("bad-id");
    }
  });

  test("the greatest id is admitted, compared as text", () => {
    for (const id of ["9223372036854775807", "0"]) {
      expect(problemOf(wire(1, withIds(id)))).toBeUndefined();
    }
  });

  test("two shards share an id", () => {
    expect(
      problemOf(
        wire(2, (a) => {
          a[1] = { ...(a[1] as WireShardAssignment), shard: "0" };
        }),
      ),
    ).toBe("duplicate-id");
  });

  test("a bad id is reported before a duplicate", () => {
    expect(problemOf(wire(3, withIds("0", "0", "x")))).toBe("bad-id");
  });

  test("a shard has no hash range", () => {
    expect(
      problemOf(
        wire(1, (a) => {
          const { shard, leader } = a[0] as WireShardAssignment;
          a[0] = { shard, leader };
        }),
      ),
    ).toBe("no-hash-range");
    expect(
      problemOf(
        wire(1, (a) => {
          a[0] = { ...(a[0] as WireShardAssignment), int32_hash_range: null } as unknown as WireShardAssignment;
        }),
      ),
    ).toBe("no-hash-range");
  });

  test("a gap", () => {
    expect(problemOf(wire(2, shiftSecondMin(1)))).toBe("range-gap-or-overlap");
  });

  test("an overlap", () => {
    expect(problemOf(wire(2, shiftSecondMin(-1)))).toBe("range-gap-or-overlap");
  });

  test("the first range does not start at 0", () => {
    expect(problemOf(wire(1, withRange(1, 0xffffffff)))).toBe("range-gap-or-overlap");
  });

  test("min above max", () => {
    expect(problemOf(wire(1, withRange(5, 4)))).toBe("range-gap-or-overlap");
    // An empty range whose ends meet its neighbours': min is the previous max + 1 and the next min is its max + 1,
    // so only the min-above-max rule refuses it.
    const empty = (assignments: WireShardAssignment[]) => {
      const second = assignments[1] as WireShardAssignment;
      const min = (second.int32_hash_range as NonNullable<WireShardAssignment["int32_hash_range"]>).min_hash_inclusive;
      assignments.splice(1, 0, {
        shard: "2",
        leader: second.leader,
        int32_hash_range: { min_hash_inclusive: min, max_hash_inclusive: min - 1 },
      });
    };
    expect(problemOf(wire(2, empty))).toBe("range-gap-or-overlap");
  });

  test("the last range does not end at 4294967295", () => {
    expect(problemOf(wire(1, withRange(0, 4294967294)))).toBe("range-gap-or-overlap");
  });

  test("the key router is not XXHASH3", () => {
    expect(problemOf(wire(1, undefined, "UNKNOWN"))).toBe("router");
  });

  test("a leader over 300 bytes", () => {
    const over = `${"a".repeat(OXIA_LEADER_MAX_BYTES - 4)}:6648`;
    expect(new TextEncoder().encode(over).length).toBe(OXIA_LEADER_MAX_BYTES + 1);
    expect(parseLeader(over)).toBeDefined();
    expect(problemOf(wire(1, withLeader(over)))).toBe("leader");
    const at = `${"a".repeat(OXIA_LEADER_MAX_BYTES - 5)}:6648`;
    expect(new TextEncoder().encode(at).length).toBe(OXIA_LEADER_MAX_BYTES);
    expect(problemOf(wire(1, withLeader(at)))).toBeUndefined();
  });

  test("a leader the parser refuses", () => {
    for (const leader of ["http://x:1", "unix:/x", "host:0", "host:99999", "host"]) {
      expect(problemOf(wire(1, withLeader(leader)))).toBe("leader");
    }
  });

  test("the leader bound counts bytes, not characters", () => {
    const leader = `${"ü".repeat(150)}:6648`;
    const answer = validateAssignments(wire(1, withLeader(leader)), "default", () => ({ host: "x", port: 1 }));
    expect("problem" in answer ? answer.problem : undefined).toBe("leader");
  });

  test("allowed_authorities is never read", () => {
    const message = { ...wire(1), allowed_authorities: ["evil.example:1"] } as WireAssignments;
    expect(validateAssignments(message, "default", parseLeader)).toEqual(
      validateAssignments(wire(1), "default", parseLeader),
    );
  });

  test("rule order: the router is checked after the ranges, the leaders last", () => {
    const bad = (gap: boolean, router: string) =>
      wire(
        2,
        (a) => {
          withLeader("host")(a);
          if (gap) shiftSecondMin(1)(a);
        },
        router,
      );
    expect(problemOf(bad(true, "UNKNOWN"))).toBe("range-gap-or-overlap");
    expect(problemOf(bad(false, "UNKNOWN"))).toBe("router");
    expect(problemOf(bad(false, "XXHASH3"))).toBe("leader");
  });

  test("the message is not mutated by the sort", () => {
    const message = wire(3, (a) => a.reverse());
    validateAssignments(message, "default", parseLeader);
    expect(message.namespaces.default?.assignments.map((assignment) => assignment.shard)).toEqual(["2", "1", "0"]);
  });
});

describe("SNAPSHOT_PROBLEM_REASONS", () => {
  test("the closed list of SB1-5.2, in the union's order", () => {
    expect(SNAPSHOT_PROBLEM_REASONS).toEqual({
      "namespace-missing": "the namespace is missing from the answer",
      "too-many-shards": "more than 1,024 shards",
      "no-shards": "no shards",
      "duplicate-id": "two shards share an id",
      "bad-id": "a shard id is not a 64-bit integer",
      "no-hash-range": "a shard has no hash range",
      "range-gap-or-overlap": "the hash ranges leave a gap or overlap",
      router: "the key router is not XXHASH3",
      leader: "a leader address is not host:port within 300 bytes",
    });
    expect(Object.keys(SNAPSHOT_PROBLEM_REASONS)).toEqual([
      "namespace-missing",
      "too-many-shards",
      "no-shards",
      "duplicate-id",
      "bad-id",
      "no-hash-range",
      "range-gap-or-overlap",
      "router",
      "leader",
    ]);
  });
});

describe("xxh3Low32 and oxiaHash (SB1-5.6)", () => {
  test("the server's own hash_test.go vectors", () => {
    expect(fixture.server.length).toBe(3);
    for (const { text, low32 } of fixture.server) expect(oxiaHash(text)).toBe(low32);
    for (const [text, low32] of Object.entries(SERVER_VECTORS)) expect(oxiaHash(text)).toBe(low32);
  });

  test("the research's measured vectors", () => {
    for (const [text, low32] of Object.entries(RESEARCH_VECTORS)) expect(oxiaHash(text)).toBe(low32);
    expect(fixture.measured.length).toBeGreaterThanOrEqual(6 + 19);
    for (const { text, low32 } of fixture.measured) expect(oxiaHash(text)).toBe(low32);
  });

  test("every length class, against the tool's XXH3-64", () => {
    const expected = [
      ...Array.from({ length: 257 }, (_, index) => index),
      257,
      511,
      1023,
      1024,
      1025,
      2048,
      4096,
      10000,
    ];
    expect(fixture.generated.map((row) => row.length)).toEqual(expected);
    for (const row of fixture.generated) {
      expect(row.xxh3).toMatch(/^[0-9a-f]{16}$/);
      const bytes = Uint8Array.from({ length: row.length }, (_, index) => (index * 31 + row.length) & 0xff);
      expect(xxh3Low32(bytes)).toBe(Number.parseInt(row.xxh3.slice(8), 16));
    }
  });

  test("the fixture says where it came from", () => {
    const { header } = fixture;
    expect(header.tool).toBe("@node-rs/xxhash");
    expect(header.toolVersion).toBe("1.7.6");
    expect(header.node).toMatch(/^v\d+\./);
    expect(typeof header.command).toBe("string");
    expect(header.command.length).toBeGreaterThan(0);
    expect(header.crossCheck.image).toBe("oxia/oxia:0.16.10");
    expect(header.crossCheck.digest).toMatch(/^(oxia\/oxia@)?sha256:[0-9a-f]{64}$/);
    expect(header.crossCheck.shards).toBeGreaterThanOrEqual(2);
    expect(header.crossCheck.cliCommand).toContain("oxia client");
    expect(header.crossCheck.onPredictedShard).toBe(header.crossCheck.keys);
    expect(header.crossCheck.onPredictedShard).toBeGreaterThanOrEqual(19);
  });

  test("a subarray hashes as its own bytes", () => {
    expect(xxh3Low32(new Uint8Array([9, 102, 111, 111, 9]).subarray(1, 4))).toBe(125730186);
  });
});

describe("shardFor", () => {
  const two = snapshot([
    [0, 2147483647],
    [2147483648, 4294967295],
  ]);

  test("two shards, the server's bucket boundaries", () => {
    expect(shardFor(two, "foo").id).toBe("0");
    expect(shardFor(two, "bar").id).toBe("1");
  });

  test("four shards", () => {
    const four = evenSnapshot(4);
    expect(four.shards[1]?.minHash).toBe(1073741824);
    for (const key of ["foo", "baz", "a", "", "/a/b"]) expect(shardFor(four, key).id).toBe("0");
    expect(shardFor(four, "key-1").id).toBe("1");
    for (const key of ["bar", "__oxia/x"]) expect(shardFor(four, key).id).toBe("2");
    expect(shardFor(four, "ünïcode").id).toBe("3");
  });

  test("a hash exactly on a boundary", () => {
    const h = 125730186;
    expect(
      shardFor(
        snapshot([
          [0, h],
          [h + 1, 4294967295],
        ]),
        "foo",
      ).id,
    ).toBe("0");
    expect(
      shardFor(
        snapshot([
          [0, h - 1],
          [h, 4294967295],
        ]),
        "foo",
      ).id,
    ).toBe("1");
  });

  test("the ends of the hash space", () => {
    const one = snapshot([[0, 4294967295]]);
    for (const text of [...Object.keys(SERVER_VECTORS), ...Object.keys(RESEARCH_VECTORS)]) {
      expect(shardFor(one, text).id).toBe("0");
    }
    const outOfOrder = evenSnapshot(4, ["7", "3", "9", "1"]);
    expect(shardFor(outOfOrder, "foo").id).toBe("7");
    expect(shardFor(outOfOrder, "key-1").id).toBe("3");
    expect(shardFor(outOfOrder, "bar").id).toBe("9");
    expect(shardFor(outOfOrder, "ünïcode").id).toBe("1");
  });

  test("a partition key routes instead of the key", () => {
    expect(shardFor(two, "foo", "bar").id).toBe("1");
    expect(shardFor(two, "bar", "foo").id).toBe("0");
    expect(shardFor(two, "bar", "").id).toBe("0");
  });

  test("1,024 shards", () => {
    const many = evenSnapshot(OXIA_MAX_SHARDS);
    expect(many.shards.length).toBe(OXIA_MAX_SHARDS);
    for (const { text } of fixture.measured) {
      const shard = shardFor(many, text);
      const hash = oxiaHash(text);
      expect(shard.minHash).toBeLessThanOrEqual(hash);
      expect(shard.maxHash).toBeGreaterThanOrEqual(hash);
    }
  });
});
