"use client";

import React, { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, Trash2, Table as TableIcon, Type, Settings2, LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import type { DatabaseType } from "@/lib/types";

interface ColumnDefinition {
  name: string;
  type: string;
  isPrimary: boolean;
  isNullable: boolean;
  isUnique: boolean;
  defaultValue: string;
}

interface CreateTableModalProps {
  isOpen: boolean;
  onClose: () => void;
  onTableCreated: (sql: string) => void;
  dbType?: DatabaseType;
}

/**
 * The `type` an auto-increment primary-key column carries in state, and deliberately not a
 * type name in any dialect.
 *
 * What the engines disagree about is not only the spelling but the SHAPE of the clause.
 * `AUTO_INCREMENT` is a column attribute that precedes `PRIMARY KEY`; SQLite's
 * `AUTOINCREMENT` is a suffix that has to FOLLOW it, and only on a column typed exactly
 * `INTEGER`; DuckDB has no keyword at all and reaches for a sequence, which is a second
 * statement. None of the three is a value the type dropdown could hold and hand to the
 * shared qualifier path below. So the column stores the user's INTENT and `generateSQL`
 * resolves it against the connected engine.
 */
const AUTO_INCREMENT = "__auto_increment__";

/**
 * Per-engine spellings for the two things this form actually offers.
 *
 * Every id below publishes `supportsCreateTable: true`, which is what puts the form in
 * front of that engine; the nine ids that publish `false` never reach it. Until #648 the
 * form ignored its own `dbType` prop and emitted one dialect for all eight — the default
 * column was `id SERIAL PRIMARY KEY` and the type list offered `JSONB`, both PostgreSQL
 * spellings.
 *
 * How each row was arrived at, because the failure modes are not all the same:
 *
 * - **`sqlite` is the reason this is a bug rather than an annoyance.** Measured on
 *   SQLite 3.53.4 (the `better-sqlite3` 13.x engine this repo pins), `CREATE TABLE t
 *   (id SERIAL PRIMARY KEY)` does NOT fail — SQLite takes any word as a type name and
 *   gives `SERIAL` NUMERIC affinity — and then two `INSERT INTO t DEFAULT VALUES` both
 *   store `id = NULL`, because only a column typed exactly `INTEGER PRIMARY KEY` is the
 *   rowid alias that auto-numbers, and SQLite's legacy rule lets a non-INTEGER primary
 *   key hold NULLs. So the old form handed SQLite users a silently broken key rather
 *   than an error. `AUTOINCREMENT` also has a fixed position there: `id INTEGER
 *   AUTOINCREMENT PRIMARY KEY` is `near "AUTOINCREMENT": syntax error` and `id BIGINT
 *   PRIMARY KEY AUTOINCREMENT` is "AUTOINCREMENT is only allowed on an INTEGER PRIMARY
 *   KEY", which is why this clause is stored whole instead of assembled from parts.
 * - **`libsql` answers as `sqlite` because it embeds it** — the same engine over a
 *   network, per the `DatabaseType` note on the id.
 * - **`duckdb` has neither keyword.** Measured on DuckDB 1.5.5 (the `@duckdb/node-api`
 *   1.5.5 the repo pins): `SERIAL` is "Type with name SERIAL does not exist",
 *   `GENERATED BY DEFAULT AS IDENTITY` is "Not implemented Error: Constraint not
 *   implemented", `AUTOINCREMENT` is a parser error, and `JSONB` is "Type with name
 *   JSONB does not exist" while `JSON` is fine. A sequence works and numbers from 1, so
 *   this is the one row that needs a statement AHEAD of the `CREATE TABLE`
 *   (`autoIncrementSequence`).
 * - **`trino` gets no auto-increment offer at all**, the way `migration-generator.ts`
 *   declines rather than emitting DDL it knows is wrong. Trino is a query engine over
 *   connectors: it declares no primary key for any table in any catalog — the same fact
 *   that makes `supportsInlineRowEdit: false` in `sql/trino/index.ts` — so there is no
 *   key for a generated value to be, and the engine has no sequence object to default
 *   from either. Its `CREATE TABLE` column grammar is a name, a type and an optional
 *   `NOT NULL`, which takes `PRIMARY KEY` and `UNIQUE` with it (`supportsConstraints`):
 *   an engine that cannot express what a checkbox means should not offer the checkbox.
 * - **`postgres`, `mysql`, `mssql` and `oracle`** carry the spelling each vendor
 *   documents as the current one. PostgreSQL's own docs call `SERIAL` historical and
 *   point at identity columns, which is why `postgres` moves too rather than keeping the
 *   text it already emitted.
 *
 * The type lists change only where the engine disagrees; a row that reads like the old
 * shared list is that engine agreeing with it, not a row nobody looked at.
 */
interface CreateTableDialect {
  /**
   * Everything after the column NAME for an auto-increment primary key, `PRIMARY KEY`
   * included, or null when the engine cannot express one. Null also hides the option.
   */
  autoIncrement: string | null;
  /** DuckDB alone: the clause defaults from a sequence, which the form has to create first. */
  autoIncrementSequence?: true;
  /**
   * Whether `PRIMARY KEY` and `UNIQUE` are column constraints this engine's `CREATE TABLE`
   * takes at all. Trino is the one that says no, and it is the same fact that removes its
   * auto-increment: its column grammar is a name, a type and an optional `NOT NULL`, so
   * the PK and Unique checkboxes have nothing to compile to and are not shown. `NOT NULL`
   * stays, because that one Trino does have.
   */
  supportsConstraints: boolean;
  /**
   * The plain integer type an `id` column carries when it is NOT an auto-increment key:
   * `trino`, which has none, and any column the user takes the PK off. It has to be one of
   * the names in `types` below or the dropdown trigger renders empty, which is why `mysql`
   * and `mssql` say `INT` rather than the `INTEGER` both would also accept as SQL.
   */
  keyType: string;
  /** The types this engine actually has, in the order the dropdown lists them. */
  types: readonly string[];
}

const SQLITE_DIALECT: CreateTableDialect = {
  autoIncrement: "INTEGER PRIMARY KEY AUTOINCREMENT",
  supportsConstraints: true,
  keyType: "INTEGER",
  // SQLite has no JSON type — `json_*()` reads and writes TEXT — and no UUID or BOOLEAN
  // type either; the names below are the five affinities plus the spellings its own docs
  // use, rather than words it would accept and quietly file under NUMERIC.
  types: ["TEXT", "INTEGER", "REAL", "BLOB", "NUMERIC"],
};

const POSTGRES_DIALECT: CreateTableDialect = {
  autoIncrement: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  supportsConstraints: true,
  keyType: "INTEGER",
  types: [
    "VARCHAR(255)",
    "TEXT",
    "INTEGER",
    "BIGINT",
    "BOOLEAN",
    "TIMESTAMP",
    "DATE",
    "JSONB",
    "UUID",
    "DECIMAL(10,2)",
  ],
};

/** Only the eight ids that publish `supportsCreateTable: true` have a row; the rest never reach this form. */
const DIALECTS: Partial<Record<DatabaseType, CreateTableDialect>> = {
  postgres: POSTGRES_DIALECT,
  mysql: {
    autoIncrement: "INT AUTO_INCREMENT PRIMARY KEY",
    supportsConstraints: true,
    keyType: "INT",
    // `JSON` since 5.7, and no `UUID` type: the docs' own recommendation for one is a
    // fixed-width `CHAR(36)` (or `BINARY(16)` via `UUID_TO_BIN`).
    types: [
      "VARCHAR(255)",
      "TEXT",
      "INT",
      "BIGINT",
      "BOOLEAN",
      "TIMESTAMP",
      "DATE",
      "JSON",
      "CHAR(36)",
      "DECIMAL(10,2)",
    ],
  },
  mssql: {
    autoIncrement: "INT IDENTITY(1,1) PRIMARY KEY",
    supportsConstraints: true,
    keyType: "INT",
    // No `BOOLEAN` (that is `BIT`), no `UUID` (`UNIQUEIDENTIFIER`), and `TIMESTAMP` is a
    // trap rather than a missing name: it is a deprecated synonym for `ROWVERSION`, a
    // row-change counter that holds no date at all, so a column meaning "a moment in
    // time" has to say `DATETIME2`. JSON is stored in `NVARCHAR(MAX)` — the native `json`
    // type is SQL Server 2025 and this repo's compose pins 2022 — so the text entry
    // serves both and is listed once.
    types: [
      "VARCHAR(255)",
      "NVARCHAR(MAX)",
      "INT",
      "BIGINT",
      "BIT",
      "DATETIME2",
      "DATE",
      "UNIQUEIDENTIFIER",
      "DECIMAL(10,2)",
    ],
  },
  oracle: {
    autoIncrement: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    supportsConstraints: true,
    keyType: "INTEGER",
    // `VARCHAR2` is the one Oracle documents (`VARCHAR` is reserved for a future meaning),
    // there is no `TEXT`/`BIGINT`/`UUID`, and `BOOLEAN` in a table column is 23ai and
    // later — `NUMBER(1)` is the spelling that works on the versions before it. JSON is
    // `CLOB` for the same reason: the native `JSON` type is 21c and later.
    types: [
      "VARCHAR2(255)",
      "CLOB",
      "INTEGER",
      "NUMBER(19)",
      "NUMBER(1)",
      "TIMESTAMP",
      "DATE",
      "RAW(16)",
      "NUMBER(10,2)",
    ],
  },
  sqlite: SQLITE_DIALECT,
  libsql: SQLITE_DIALECT,
  duckdb: {
    autoIncrement: "INTEGER PRIMARY KEY",
    autoIncrementSequence: true,
    supportsConstraints: true,
    keyType: "INTEGER",
    types: [
      "VARCHAR(255)",
      "TEXT",
      "INTEGER",
      "BIGINT",
      "BOOLEAN",
      "TIMESTAMP",
      "DATE",
      "JSON",
      "UUID",
      "DECIMAL(10,2)",
    ],
  },
  trino: {
    autoIncrement: null,
    supportsConstraints: false,
    keyType: "INTEGER",
    // `TEXT` is not a Trino type name; an unbounded string is `VARCHAR`.
    types: [
      "VARCHAR(255)",
      "VARCHAR",
      "INTEGER",
      "BIGINT",
      "BOOLEAN",
      "TIMESTAMP",
      "DATE",
      "JSON",
      "UUID",
      "DECIMAL(10,2)",
    ],
  },
};

/**
 * PostgreSQL is the fallback for an unknown or absent `dbType` because it is what this
 * form emitted for every engine before #648: an unconnected modal keeps the behaviour it
 * had rather than picking a new one.
 */
function resolveDialect(dbType: DatabaseType | undefined): CreateTableDialect {
  return (dbType && DIALECTS[dbType]) || POSTGRES_DIALECT;
}

/** The first column the form starts with, which is an auto-increment key wherever there is one. */
function defaultColumns(dialect: CreateTableDialect): ColumnDefinition[] {
  return [
    {
      name: "id",
      type: dialect.autoIncrement ? AUTO_INCREMENT : dialect.keyType,
      isPrimary: dialect.supportsConstraints,
      isNullable: false,
      isUnique: dialect.supportsConstraints,
      defaultValue: "",
    },
  ];
}

export function CreateTableModal({ isOpen, onClose, onTableCreated, dbType }: CreateTableModalProps) {
  const dialect = resolveDialect(dbType);
  const [tableName, setTableName] = useState("");
  const [columns, setColumns] = useState<ColumnDefinition[]>(() => defaultColumns(dialect));
  const [isSubmitting] = useState(false);

  // Columns hold dialect text — a type name, and the auto-increment sentinel — so they are
  // re-derived when the engine changes rather than carried across it. Without this the
  // initial state is whatever `dbType` was on the FIRST render, and `Studio.tsx` renders
  // this modal unconditionally with `dbType={conn.activeConnection?.type}`: that first
  // render is always `undefined` -> the PostgreSQL fallback, on every engine. So Trino got
  // a column on a sentinel it has no clause for (empty type dropdown), and the reset in
  // `handleCreate` then froze each engine's default into the next connection.
  const [renderedFor, setRenderedFor] = useState(dbType);
  if (renderedFor !== dbType) {
    setRenderedFor(dbType);
    setColumns(defaultColumns(dialect));
  }

  const addColumn = () => {
    setColumns([
      ...columns,
      {
        name: "",
        // The engine's own first type, so an added column starts on a name it has:
        // "VARCHAR(255)" is not one on SQLite's list.
        type: dialect.types[0],
        isPrimary: false,
        isNullable: true,
        isUnique: false,
        defaultValue: "",
      },
    ]);
  };

  const removeColumn = (index: number) => {
    if (columns.length === 1) return;
    setColumns(columns.filter((_, i) => i !== index));
  };

  const updateColumn = (index: number, updates: Partial<ColumnDefinition>) => {
    setColumns(columns.map((col, i) => (i === index ? { ...col, ...updates } : col)));
  };

  const generateSQL = () => {
    if (!tableName.trim()) return "";

    // Statements the CREATE TABLE depends on. Only DuckDB has one, and `executeQuery`
    // routes a multi-statement buffer to `/api/db/multi-query`, which splits on the
    // dialect's own grammar and runs the fragments in order.
    const prelude: string[] = [];

    const colDefs = columns.map((col) => {
      // An auto-increment key is a whole column clause rather than a type, because each
      // engine puts PRIMARY KEY in a different place inside it. It cannot go through the
      // qualifier path below: appending " PRIMARY KEY" to SQLite's clause would give
      // `INTEGER PRIMARY KEY AUTOINCREMENT PRIMARY KEY`.
      // `col.isPrimary` gates it because the clause SPELLS `PRIMARY KEY` itself: without
      // that read, unchecking PK on this column left the key in the SQL while the form
      // said it was gone, and the two disagreed with no way back.
      if (col.type === AUTO_INCREMENT && col.isPrimary && dialect.autoIncrement) {
        let clause = `${col.name} ${dialect.autoIncrement}`;
        if (dialect.autoIncrementSequence) {
          // `IF NOT EXISTS` because a DuckDB sequence OUTLIVES the table that defaults
          // from it: measured on 1.5.5, `DROP TABLE widgets` leaves `widgets_id_seq`
          // behind (`nextval` on it still answers), and a plain `CREATE SEQUENCE` then
          // fails with `Sequence with name "widgets_id_seq" already exists!`. Without the
          // guard, creating a table, dropping it and creating it again through this form
          // fails the second time. The surviving sequence resumes its count, which costs
          // a few ids and nothing else.
          const sequence = `${tableName}_${col.name}_seq`;
          prelude.push(`CREATE SEQUENCE IF NOT EXISTS ${sequence};`);
          clause += ` DEFAULT nextval('${sequence}')`;
        }
        return `  ${clause}`;
      }

      // A column still on the sentinel here is one the key was taken off, or one whose
      // engine has no auto-increment clause. Either way emit the plain integer type rather
      // than the sentinel text.
      const type = col.type === AUTO_INCREMENT ? dialect.keyType : col.type;
      // `isPrimary` also gates NOT NULL and UNIQUE below, so an engine without constraints
      // has to read it as false here rather than merely skip the PRIMARY KEY line -
      // otherwise a key column silently loses its NOT NULL as well.
      const isPrimary = col.isPrimary && dialect.supportsConstraints;
      let def = `${col.name} ${type}`;
      if (isPrimary) def += " PRIMARY KEY";
      if (!col.isNullable && !isPrimary) def += " NOT NULL";
      if (col.isUnique && !isPrimary && dialect.supportsConstraints) def += " UNIQUE";
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      return `  ${def}`;
    });

    const create = `CREATE TABLE ${tableName} (\n${colDefs.join(",\n")}\n);`;
    return prelude.length ? `${prelude.join("\n")}\n${create}` : create;
  };

  const handleCreate = async () => {
    // The name check is unreachable via the UI (the input sanitizes whitespace
    // to "_" and the button disables on empty); kept for imperative callers.
    const nameError = tableName.trim() ? "" : "Table name is required";
    const columnError = columns.some((c) => !c.name.trim()) ? "All columns must have a name" : "";
    const validationError = nameError || columnError;
    if (validationError) {
      toast.error(validationError);
      return;
    }

    const sql = generateSQL();
    onTableCreated(sql);
    onClose();
    setTableName("");
    setColumns(defaultColumns(dialect));
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl bg-surface border-hairline-strong text-fg p-0 overflow-hidden flex flex-col max-h-[90vh]">
        <DialogHeader className="px-6 py-4 border-b border-hairline bg-panel">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-brand-tint/10 border border-brand-tint/20">
              <TableIcon strokeWidth={1.5} className="w-5 h-5 text-brand" />
            </div>
            <div>
              <DialogTitle className="text-xs font-medium">Create New Table</DialogTitle>
              <p className="text-xs text-fg-muted mt-1 font-medium">Define schema structure</p>
            </div>
          </div>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
          {/* Table Name Section */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Settings2 strokeWidth={1.5} className="w-3.5 h-3.5 text-brand/50" />
              <Label className="text-xs font-medium text-fg-muted">General Settings</Label>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="tableName" className="text-xs font-medium text-fg-tertiary">
                Table Name
              </Label>
              <Input
                id="tableName"
                placeholder="e.g. customers, orders, analytics_logs"
                value={tableName}
                onChange={(e) => setTableName(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "_"))}
                className="bg-raised border-hairline focus-visible:ring-brand-tint/50"
              />
            </div>
          </div>

          {/* Columns Section */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Type strokeWidth={1.5} className="w-3.5 h-3.5 text-success/50" />
                <Label className="text-xs font-medium text-fg-muted">Column Definitions</Label>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={addColumn}
                className="h-7 text-xs font-medium gap-2 hover:bg-success-tint/10 hover:text-success"
              >
                <Plus strokeWidth={1.5} className="w-3 h-3" /> Add Column
              </Button>
            </div>

            <div className="space-y-3">
              {columns.map((col, index) => (
                <div
                  key={index}
                  className="flex items-end gap-3 p-3 rounded-lg bg-panel border border-hairline group hover:border-hairline-strong transition-colors"
                >
                  <div className="flex-1 space-y-2">
                    <Label className="text-xs text-fg-muted font-medium">Column Name</Label>
                    <Input
                      value={col.name}
                      onChange={(e) =>
                        updateColumn(index, { name: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "_") })
                      }
                      placeholder="column_name"
                      className="h-8 text-xs bg-surface border-hairline"
                    />
                  </div>

                  <div className="w-40 space-y-2">
                    <Label className="text-xs text-fg-muted font-medium">Type</Label>
                    <Select value={col.type} onValueChange={(val) => updateColumn(index, { type: val })}>
                      <SelectTrigger className="h-8 text-xs bg-surface border-hairline">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-surface border-hairline-strong">
                        {dialect.types.map((t) => (
                          <SelectItem key={t} value={t} className="text-xs">
                            {t}
                          </SelectItem>
                        ))}
                        {col.isPrimary && dialect.autoIncrement && (
                          <SelectItem value={AUTO_INCREMENT} className="text-xs text-hue-yellow">
                            Auto-Increment
                          </SelectItem>
                        )}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="flex items-center gap-4 pb-2 px-2">
                    {dialect.supportsConstraints && (
                      <div className="flex flex-col items-center gap-1.5" title="Primary Key">
                        <Label className="text-[0.5rem] text-fg-subtle uppercase font-black">PK</Label>
                        <Checkbox
                          checked={col.isPrimary}
                          onCheckedChange={(checked) =>
                            updateColumn(index, {
                              isPrimary: !!checked,
                              isNullable: checked ? false : col.isNullable,
                              // Auto-Increment is only offered ON a primary key, so taking
                              // the key off has to take the column off that entry too —
                              // the dropdown stops listing it at the same click, and a
                              // trigger left on it renders empty.
                              type: !checked && col.type === AUTO_INCREMENT ? dialect.keyType : col.type,
                            })
                          }
                          className="border-edge data-[state=checked]:bg-hue-yellow-tint data-[state=checked]:border-hue-yellow-tint"
                        />
                      </div>
                    )}
                    <div className="flex flex-col items-center gap-1.5" title="Nullable">
                      <Label className="text-[0.5rem] text-fg-subtle uppercase font-black">Null</Label>
                      <Checkbox
                        checked={col.isNullable}
                        onCheckedChange={(checked) => updateColumn(index, { isNullable: !!checked })}
                        className="border-edge data-[state=checked]:bg-hue-blue-tint data-[state=checked]:border-hue-blue-tint"
                      />
                    </div>
                    {dialect.supportsConstraints && (
                      <div className="flex flex-col items-center gap-1.5" title="Unique">
                        <Label className="text-[0.5rem] text-fg-subtle uppercase font-black">Unq</Label>
                        <Checkbox
                          checked={col.isUnique}
                          onCheckedChange={(checked) => updateColumn(index, { isUnique: !!checked })}
                          className="border-edge data-[state=checked]:bg-hue-purple-tint data-[state=checked]:border-hue-purple-tint"
                        />
                      </div>
                    )}
                  </div>

                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 text-fg-subtle hover:text-danger hover:bg-danger-tint/10 mb-0.5"
                    onClick={() => removeColumn(index)}
                    aria-label={`Remove column ${index + 1}`}
                  >
                    <Trash2 strokeWidth={1.5} className="w-3.5 h-3.5" />
                  </Button>
                </div>
              ))}
            </div>
          </div>

          {/*
            A terminal, not a panel: the ground is a hard `bg-black` in both themes,
            so the tokens inside it have to resolve their DARK values or the light
            palette paints dark-on-black. Scoped the way the login hero scopes its
            own pinned-dark column (#402).
          */}
          <div className="dark p-4 rounded-lg bg-black border border-hairline font-mono">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-brand-tint" />
                <span className="text-xs font-medium text-fg-muted">SQL Preview</span>
              </div>
              <span className="text-[0.625rem] text-fg-faint">Auto-generated</span>
            </div>
            <pre className="text-xs text-brand/80 whitespace-pre-wrap leading-relaxed">
              {generateSQL() || "-- Name your table to see SQL"}
            </pre>
          </div>
        </div>

        <DialogFooter className="px-6 py-4 border-t border-hairline bg-panel">
          <Button variant="ghost" onClick={onClose} className="text-xs text-fg-tertiary hover:text-fg-bright">
            Cancel
          </Button>
          <Button
            onClick={handleCreate}
            disabled={isSubmitting || !tableName}
            className="bg-brand-solid hover:bg-brand-solid-hover text-white text-xs font-medium gap-2 px-6"
          >
            {isSubmitting ? (
              <LoaderCircle strokeWidth={1.5} className="w-3 h-3 animate-spin" />
            ) : (
              <Plus strokeWidth={1.5} className="w-3 h-3" />
            )}
            CREATE TABLE
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
