#!/usr/bin/env bash
# ==============================================================================
# Writes THIRD_PARTY_NOTICES.txt: the license notices for the code compiled
# into db2-node's prebuilt addons (issue #786).
#
# The db2-node npm tarball ships eight `.node` files and no LICENSE, and the
# Rust crates statically linked into those files carry their own notices,
# which no npm-level tool (npm audit, Dependabot, the CycloneDX SBOM) can see.
# The file this writes is the one place those notices travel with every
# artifact: the Dockerfiles COPY it into /app and
# scripts/build-standalone-payload.sh copies it to the payload root, which
# every tarball, package and desktop bundle is built from.
#
# The crate set is what Cargo links into the db2-napi cdylib for the eight
# targets the package ships (normal edges only; proc-macro and build-time
# crates leave no code in the binary). For a crate offered under a choice that
# includes MIT, the MIT text is used; any other crate contributes every
# license file it ships. A crate whose source carries no license file is
# listed with the license its manifest declares. Line endings are normalised
# to LF, so a rerun at the same gitHead writes the same bytes.
#
# Never edit THIRD_PARTY_NOTICES.txt by hand: bumping db2-node means checking
# out the new version's gitHead (`npm view db2-node@<v> gitHead`) and running
# this again. Needs cargo and network access for `cargo tree --locked`.
#
# Usage: generate-db2-node-notices.sh <db2-node checkout> [output file]
# ==============================================================================

set -euo pipefail

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  echo "Usage: $0 <db2-node checkout> [output file]" >&2
  exit 1
fi

SRC=$(cd "$1" && pwd)
OUT=${2:-"$(cd "$(dirname "$0")/.." && pwd)/THIRD_PARTY_NOTICES.txt"}
VERSION=$(node -p "require('$(cd "$(dirname "$0")/.." && pwd)/package.json').dependencies['db2-node']")
GIT_HEAD=$(git -C "$SRC" rev-parse --short=8 HEAD)
REGISTRY=$(find "${CARGO_HOME:-$HOME/.cargo}/registry/src" -mindepth 1 -maxdepth 1 -type d | sort | head -n 1)

TARGETS=(
  x86_64-unknown-linux-gnu
  x86_64-unknown-linux-musl
  aarch64-unknown-linux-gnu
  aarch64-unknown-linux-musl
  x86_64-apple-darwin
  aarch64-apple-darwin
  x86_64-pc-windows-msvc
  aarch64-pc-windows-msvc
)

CRATES=$(
  for target in "${TARGETS[@]}"; do
    (cd "$SRC" && cargo tree -p db2-napi -e normal,no-proc-macro --target "$target" \
      --prefix none --format '{p}|{l}' --locked)
  done | grep -v '(/' | sed 's/ (\*)//' | sort -u
)

if [ ! -f "$SRC/LICENSE" ]; then
  echo "$SRC has no LICENSE file" >&2
  exit 1
fi

{
  echo "THIRD-PARTY NOTICES"
  echo
  echo "LibreDB Studio is distributed under the MIT License (see LICENSE)."
  echo "This file carries the notices for third-party code that is compiled into a"
  echo "shipped binary and whose package does not carry those notices itself."
  echo "Generated by scripts/generate-db2-node-notices.sh; do not edit by hand."
  echo
  echo "================================================================================"
  echo "db2-node ${VERSION} (https://github.com/gurungabit/db2-node, gitHead ${GIT_HEAD})"
  echo "License: MIT"
  echo "================================================================================"
  echo
  cat "$SRC/LICENSE"
  echo
  echo "The prebuilt db2-node.<platform>.node addons statically link the Rust crates"
  echo "below. None of them ships a NOTICE file."
  while IFS='|' read -r package license; do
    name=${package%% *}
    version=${package#* v}
    dir="$REGISTRY/$name-$version"
    if [ ! -d "$dir" ]; then
      echo "Crate source not found: $dir" >&2
      exit 1
    fi
    if [ -n "$(find "$dir" -maxdepth 1 -iname 'notice*')" ]; then
      echo "$name $version ships a NOTICE file; carry it here before shipping" >&2
      exit 1
    fi
    echo
    echo "--------------------------------------------------------------------------------"
    echo "${name} ${version}"
    echo "License: ${license}"
    echo "--------------------------------------------------------------------------------"
    mit=$(find "$dir" -maxdepth 1 -type f \( -iname 'license-mit' -o -iname 'license-mit.md' -o -iname 'license-mit.txt' \) | head -n 1)
    if [[ "$license" == *" OR "* && "$license" == *MIT* && -n "$mit" ]]; then
      echo "Used under the MIT License."
      echo
      cat "$mit"
      continue
    fi
    files=$(find "$dir" -maxdepth 1 -type f \( -iname 'licen[cs]e*' -o -iname 'copying*' -o -iname 'unlicense*' \) | LC_ALL=C sort)
    if [ -z "$files" ]; then
      echo "The crate source ships no license file; its manifest declares ${license}."
      continue
    fi
    while IFS= read -r file; do
      echo
      echo "[$(basename "$file")]"
      cat "$file"
    done <<<"$files"
  done <<<"$CRATES"
} | sed 's/\r$//' >"$OUT"

echo "Wrote $OUT ($(grep -c '^License: ' "$OUT") license blocks)"
