/**
 * The two seeds' Python packages (vector-family spec 7.1 and 7.2): each seed one-shot installs exactly the packages
 * its requirements.in pins, from a requirements.txt that docker/lock-requirements.sh generated for the seed's pinned
 * image, every line one version and one wheel hash, so `pip install --require-hashes` takes nothing else.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dir, "../../../..");

interface Seed {
  readonly engine: "milvus" | "qdrant";
  readonly image: string;
  readonly pinned: readonly string[];
  readonly count: number;
}

const SEEDS: readonly Seed[] = [
  {
    engine: "milvus",
    image: "python:3.12-slim@sha256:dddfd7e07f9d15aeeca61529320492139d21cac7f0070c00609243e51e4e0016",
    pinned: ["pymilvus==3.0.2", "numpy==2.5.3", "ml-dtypes==0.6.0"],
    count: 17,
  },
  {
    engine: "qdrant",
    image: "python:3.14-slim@sha256:0741d101873c12ab927e6f8653feb8862b9bd58771177acb1b885b95141f91b4",
    pinned: ["qdrant-client==1.19.1", "numpy==2.5.3"],
    count: 20,
  },
];

/** A package name as pip compares it: lower case, every run of "-", "_" and "." one "-". */
const normalise = (name: string): string => name.toLowerCase().replace(/[-_.]+/g, "-");

function pins(file: string): string[] {
  return readFileSync(file, "utf8")
    .split("\n")
    .filter((line) => line.trim() !== "" && !line.startsWith("#"))
    .map((line) => {
      const match = /^([A-Za-z0-9_.-]+)==(\S+)/.exec(line);
      if (match === null) throw new Error(`${file}: "${line}" is not one pinned package`);
      return `${normalise(match[1])}==${match[2]}`;
    })
    .sort();
}

for (const { engine, image, pinned, count } of SEEDS) {
  describe(`the ${engine} seed's packages`, () => {
    const directory = path.join(ROOT, "docker", engine);

    test("requirements.in pins every package once, the seed's own versions among them", () => {
      const all = pins(path.join(directory, "requirements.in"));
      expect(all).toHaveLength(count);
      expect(new Set(all.map((pin) => pin.split("==")[0])).size).toBe(count);
      for (const pin of pinned) expect(all).toContain(pin);
    });

    test("requirements.txt is generated for the seed's image and holds the same pins, each with one wheel hash", () => {
      const lines = readFileSync(path.join(directory, "requirements.txt"), "utf8").trimEnd().split("\n");
      expect(lines[0]).toBe(
        `# Generated by docker/lock-requirements.sh from requirements.in for ${image}; never edit by hand.`,
      );
      for (const line of lines.slice(1)) expect(line).toMatch(/^[A-Za-z0-9_.]+==\S+ --hash=sha256:[0-9a-f]{64}$/);
      expect(pins(path.join(directory, "requirements.txt"))).toEqual(pins(path.join(directory, "requirements.in")));
    });
  });
}
